

apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: git-clone- 
  labels: 
    tekton.dev/task: git-clone
spec:
  podTemplate:
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
  taskRef:
    name: git-clone
  params: 
    - name: url
      value: https://github.com/kennedn/CICD-Demo
    - name: revision
      value: spring
    - name: userHome
      value: /home/nonroot
  workspaces: 
    - name: output
      persistentVolumeClaim:
        claimName: tekton-tutorial-sources

