apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven-pipeline
spec:
  workspaces:
  - name: shared-workspace
  - name: maven-settings
  params:
  - name: GITHUB_REPO_URL
    description: >-
      The GitHub Repo of the Java Application
  - name: GITHUB_REPO_REVISION
    description: >-
      The GitHub revision to use
    default: master
  - name: MAVEN_CONTEXT
    description: >-
      The directory within the repository on which we want to execute maven goals
  - name: BUILDAH_REPO_URL
    description: >-
      The fully qualified image name e.g example.com/tekton-tutorial/greeter
  - name: BUILDAH_CONTEXT
    description: >-
      The base directory in which to run buildah commands
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.GITHUB_REPO_URL)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.GITHUB_REPO_REVISION)
  - name: build-java-test
    taskRef:
      name: maven
      kind: ClusterTask
    params:
    - name: GOALS
      value:
        - '-B'
        - 'test'
      name: CONTEXT_DIR
      value: $(params.MAVEN_CONTEXT)
    workspaces:
    - name: maven-settings
      workspace: maven-settings
    - name: source
      workspace: shared-workspace
    runAfter:
    - fetch-repository 
  - name: build-java
    taskRef:
      name: maven
      kind: ClusterTask
    params:
    - name: GOALS
      value:
        - '-B'
        - '-DskipTests'
        - 'package'
      name: CONTEXT_DIR
      value: $(params.MAVEN_CONTEXT)
    workspaces:
    - name: maven-settings
      workspace: maven-settings
    - name: source
      workspace: shared-workspace
    runAfter:
    - build-java-test
  - name: build-image
    taskRef:
      name: buildah
      kind: ClusterTask
    params:
    - name: IMAGE
      value: $(params.BUILDAH_REPO_URL)
    - name: CONTEXT
      value: $(params.BUILDAH_CONTEXT)
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - build-java