apiVersion: tekton.dev/v1beta1 
kind: PipelineRun 
metadata:
  generateName: maven-taskrun-
spec:
  podTemplate:
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
  pipelineRef:
    name: maven-pipeline
  params: 
  - name: GITHUB_REPO_REVISION
    value: spring
  - name: CONTEXT_DIR
    value: src/spring-petclinic
  workspaces: 
  - name: maven
    subPath: maven
    persistentVolumeClaim:
      claimName: tekton-tutorial-sources
  - name: shared-workspace
    subPath: source
    persistentVolumeClaim:
      claimName: tekton-tutorial-sources