apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: petclinic-build
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.url)
  - name: git-revision
    value: $(body.head_commit.id)